### ISSUE TITLE
authManager unable to invoke some tokenGetter dependencies

### ISSUE THREAD

**Issue by kshaaban-** [auth0/angular-jwt#92] opened 2016-08-20 20:20 UTC
For example, when I use the example provided in the docs to bypass sending JWTs for template requests:

UPDATE: [a Plunker demonstrating the issue](https://plnkr.co/edit/DmT1UoyzojPPJmztmMVc?p=preview)

**config.js**
```javascript
(function() {
    'use strict';

    angular
        .module('app.core')
        .config(appConfig);

    appConfig.$inject = ['$httpProvider', '$ionicConfigProvider', '$localStorageProvider', 'jwtOptionsProvider', 'API'];

    function appConfig($httpProvider, $ionicConfigProvider, $localStorageProvider, jwtOptionsProvider, API) {
        // ~snipped~

        // JWT Interceptor
        $httpProvider.interceptors.push('jwtInterceptor');

        // JWT Configration Options
        jwtOptionsProvider.config({
            // options here are the request options
            tokenGetter: ['options', '$localStorage', function(options, $localStorage) {
                var token = null;
                if (options.url.substr(options.url.length - 5) !== '.html') {
                    token = $localStorage.token;
                }
                return token;
            }],
            whiteListedDomains: [
                API.BASE
            ]
        });
    }
})();
```

And injecting the authManager and calling its `checkAuthOnRefresh()` during the `run` phase:

**app.js**
```javascript
(function() {
    'use strict';

    angular
        .module('app', [
            'app.core',
            // ~snipped~
        ])

        .run(bootstrapApp);

    bootstrapApp.$inject = ['$ionicPlatform', 'authManager', 'amMoment'];

    /* @ngInject */
    function bootstrapApp($ionicPlatform, authManager, amMoment) {
        authManager.checkAuthOnRefresh();

        // ~snipped~
    }
})();
```

I get an error saying that 'optionsProvider' is unavailable when invoked from the authManager:
```
Error: [$injector:unpr] Unknown provider: optionsProvider <- options
```
The options are available to the tokenGetter when making requests though.

**Comment by ashishtilara** [comment] 2016-08-25 06:43
+1

**Comment by majid701** [comment] 2016-08-30 13:32
I'm having the same problem but only when i use `authManager.checkAuthOnRefresh();` 
Everything works but the error that shows up in the console is just annoying. Please fix this soon thanks.

**Comment by jromero-onclick** [comment] 2016-08-30 16:10
+1

**Comment by jromero-onclick** [comment] 2016-08-30 16:23
I think the problem is within the invoke of the tokenGetter, so it should inject the dependency 'options' and it did not:

```
function checkAuthOnRefresh() {
        $rootScope.$on('$locationChangeStart', function () {
          var tokenGetter = config.tokenGetter;
          var token = null;
          if (Array.isArray(tokenGetter)) {
            token = $injector.invoke(tokenGetter, this, {});
          } else {
            token = config.tokenGetter();
          }
          if (token) {
            if (!jwtHelper.isTokenExpired(token)) {
              authenticate();
            }
          }
        });
      }
```

....

```
          var tokenPromise = $q.when($injector.invoke(options.tokenGetter, this, {
            options: request
          }));
```

**Comment by chenkie** [comment] 2016-09-06 17:52
@kshaaban- and others experiencing this, we weren't able to reproduce this. Are you able to provide something reproducible? Thanks!

**Comment by gabrieleciech** [comment] 2016-09-07 08:02
Having the same issue as @majid701 pointed out. How can we provide you something reproducible?

**Comment by kshaaban-** [comment] 2016-09-07 14:36
@chenkie Sure thing, here's [a Plunker demonstrating the issue](https://plnkr.co/edit/DmT1UoyzojPPJmztmMVc?p=preview).

@jromero-onclick does point out the root cause behind this issue:
https://github.com/auth0/angular-jwt/blob/master/src/angularJwt/services/authManager.js#L23
```javascript
if (Array.isArray(tokenGetter)) {
    token = $injector.invoke(tokenGetter, this, {});
}
```
https://github.com/auth0/angular-jwt/blob/master/src/angularJwt/services/interceptor.js#L55-L57
```javascript
var tokenPromise = $q.when($injector.invoke(options.tokenGetter, this, {
    options: request
}));
```

Request Options can be injected into tokenGetter at the interceptor level because they are available there, but not from authManager

**Comment by kshaaban-** [comment] 2016-09-07 20:39
See the above commit in action [at this plunker](https://plnkr.co/edit/9S0ldZFg5EduupwmJ8On?p=preview).

Let me hear your feedback of this approach.

**Comment by chenkie** [comment] 2016-09-14 13:42
Thanks for putting this together @kshaaban-

The only thing I'm concerned about from an API perspective is having two separate token getters. Since most people will be retrieving the token in the same fashion for both it creates some redundancy. Can we craft it in a way that the same `tokenGetter` function is used for both?

**Comment by kshaaban-** [comment] 2016-09-14 17:59
Maybe as @sildur suggests in his PR #96.
But instead of passing `null` as `options` we pass an empty `options` with blank properties defined on it from authManager so that it doesn't error if accessed from inside `tokenGetter` ?
```javascript
// authManager.js
        if (Array.isArray(tokenGetter)) {
            var emptyOptions = {
              method:'',
              transformRequest: [null],
              transformResponse: [null],
              url: '',
              headers: {
                Accept: '',
              },
            };
            token = $injector.invoke(tokenGetter, this, {
              options: emptyOptions
            });
        }
```

The downside is that developers accessing those request options would have to revisit their `tokenGetter` logic and be **extra careful** whenever they add logic that involves checking request options.

For example, from my first message when I created the issue, my `tokenGetter` would return `null` to authManager's `checkAuthOnRefresh()` because `options.url` is empty if we take that route:
```javascript
        var token = null;
        if (options.url.substr(options.url.length - 5) !== '.html') {
            token = $localStorage.token;
        }
        return token;
```

Just a thought.

**Comment by jromero-onclick** [comment] 2016-10-03 09:21
Is there any update about the issue?

**Comment by chenkie** [comment] 2016-10-03 12:27
The fix is merged in, new release coming shortly 👍

**Comment by chenkie** [comment] 2016-10-03 13:04
Shipped the new release. Can you test with your own apps and let me know if we can close this issue?

**Comment by majid701** [comment] 2016-10-04 07:59
@chenkie Just tested the fix and seems to not work.
Giving this error: 
`TypeError: Cannot read property 'url' of null at jwtOptionsProvider.config.tokenGetter`

I gave a quick reading of the code changed by this issue particularly at line:
`if (Array.isArray(tokenGetter)) {
            token = $injector.invoke(tokenGetter, this, {options: null});`

Options is null thats why its causing the error.
Regardless the error the token getter is working fine:  Not adding the token in request headers of the ajax downloading the html template views.

Can somebody fix this?
thanks

**Comment by jromero-onclick** [comment] 2016-10-04 08:28
@majid701 I had the same problem and currently in the code I am checking if options is null before checking the url property value. **So, this is a breaking change.** In my case feets ok but I understand that for particular cases you need to check every time the properties of options object...

**Comment by majid701** [comment] 2016-10-04 08:36
@jromero-onclick  No its not null, if you console.log(options) you can see it has the property URL among with other properties but still its causing the issue. 
I'm having a look but can't seem to accomplish something working.

**Comment by adrogon** [comment] 2016-10-04 10:44
Reply from kshaaban- was correct, PR was not.

**Comment by chenkie** [comment] 2016-10-07 12:38
@majid701 @jromero-onclick you can also modify the token getter to check if `options` is there which should prevent the error:

```js
...
tokenGetter: ['options', function (options) {
  if (options && options.url.substr(options.url.length - 5) == '.html') {
    return null;
  }
  return localStorage.getItem('id_token');
}],
...
```

**Comment by kshaaban-** [comment] 2016-10-08 19:07
@chenkie 
This takes care of the issue, and I think it can be closed after [updating the docs](https://github.com/auth0/angular-jwt/pull/105) (PR #105) to note that `options` will be `null` when developers need to `authManager.checkAuthOnRefresh()`.

Thanks!

**Comment by majid701** [comment] 2016-10-09 11:48
@chenkie thanks it's working now. 
yepp the issue can be closed now.

**Comment by chenkie** [comment] 2016-10-09 13:54
awesome, thanks guys!

**Closed by chenkie** 2016-10-09 13:54 UTC
