### ISSUE TITLE
authManager.checkAuthOnRefresh not working

### ISSUE THREAD

**Issue by IagoLast** [auth0/angular-jwt#89] opened 2016-08-20 12:45 UTC
``` javascript
// src/angularJwt/services/authManager.js

function checkAuthOnRefresh() {
        // When a location change is detected
        $rootScope.$on('$locationChangeStart', function () {
          var tokenGetter = config.tokenGetter;
          var token = null;
          // Try to get jwt token...
          if (Array.isArray(tokenGetter)) {
            token = $injector.invoke(tokenGetter, this, {});
          } else {
            token = config.tokenGetter();
          }
          if (token) {
            if (!jwtHelper.isTokenExpired(token)) {
                     // If token and not expired authenticate, ok lgtm
                     authenticate();
            }
            // But what happens if not? when token had expired or there is no token? 
            // Shall an 'unauthenticated' event be fired?
          }
        });
      }
```

But there´s more... if **checkAuthOnRefresh** fires `unauthenticated` event every time that a `locationChangeStart` is produced the user won't be able to go to the login page.

( Because `redirectWhenUnauthenticated` will be fired with another `locationChangeStart` causing an infinite loop. )

**Comment by chenkie** [comment] 2016-08-20 17:32
The issue is that it's not always the case that an expired JWT (or not having a JWT) should necessitate a redirect to the login page. Many apps have routes that don't require authentication. So if a user was at one point authenticated, but now has an expired JWT, they shouldn't be redirected to the login page immediately if they are on a public route.

The better detection for this is if the user tries to access secured resources from the server. If they are at a route that accesses secured resources and they refresh the page, a 401 will be returned from the next call to the server and they will be redirected to the login page because `redirectWhenUnauthenticated` is there.

**Comment by rodneyjoyce** [comment] 2016-10-04 09:55
It would be nice if this method could provide a callback so that we could hook into it - e.g. When the token is expired, then I need to remove it from localstorage OR if I am using RefreshTokens then I could make a another call to Auth0. 

Currently I use this code to achieve this - 


        jwtInterceptorProvider.tokenGetter = function (jwtHelper) {
            var token = localStorage.getItem('id_token');
            var refreshToken = localStorage.getItem('refreshToken');
            if (token) {
                if (!jwtHelper.isTokenExpired(token)) {
                    //valid stored token - use it
                    return localStorage.getItem('id_token');
                } else {
                    console.log('id_token has expired - removing from localstorage')
                    localStorage.removeItem('id_token');
                }
            }
        }

**Comment by chenkie** [comment] 2016-11-16 01:13
There's now a `tokenHasExpired` event being fired on page refresh if the token's expiry has passed. This can be picked up and used on page refresh, but it sounds like you're needing a hook for basically any time a request gets made. 

Perhaps we can look at providing a config option for something like `onTokenExpiry` where you can provide a function to do whatever you like. It might be just as well to handle it in your `tokenGetter` at the end of the day though.

I'm going to close this particular issue but please feel free to open another one with the request for the hook you're after. PRs also welcome :)

**Closed by chenkie** 2016-11-16 01:13 UTC

**Comment by BillyFigueroa** [comment] 2017-05-12 23:29
Has anyone confirmed that this 'tokenHasExpired' event works?

I have tried this on the run block and it is not working. If I use authManger
```JavaScript
authManager.redirectWhenUnauthenticated('/login');
```
however, that works. It redirects, but if I try to alert or console.log on the event, nothing happens

**Comment by ryanwalls** [comment] 2017-10-02 23:11
@chenkie I have resources returning 403s and the app is not redirecting.  Does `authManager.redirectWhenUnauthenticated()` only work with 401s?
